In [2]:
import numpy as np

# Import .txt or .csv file

In [10]:
np.loadtxt("data.csv",delimiter=",",dtype=int)

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [3, 4, 6, 7, 3]])

In [11]:
np.genfromtxt("data.csv",delimiter=",",dtype=float)

array([[1., 2., 3., 4., 5.],
       [6., 7., 8., 9., 0.],
       [3., 4., 6., 7., 3.]])

# Make Array

In [12]:
a=np.array([1,2,3])

In [13]:
a

array([1, 2, 3])

In [16]:
lst=['a','b',3,4,5,6]
b=np.array(lst) #All datatpy in one array will be equal.(string in this case)

In [17]:
b

array(['a', 'b', '3', '4', '5', '6'], dtype='<U1')

In [18]:
array=np.array([[1,2,3],[4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
array[0][0]

1

In [21]:
array[0][0]=2
array

array([[2, 2, 3],
       [4, 5, 6]])

In [23]:
array=np.array([(1,2,3),(4,5,6)])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
array[0][0]

1

In [25]:
array[0][0]=2
array

array([[2, 2, 3],
       [4, 5, 6]])

In [26]:
array3_=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[1,8,5],[4,2,9]]])
array3_

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  8,  5],
        [ 4,  2,  9]]])

In [27]:
array.shape

(2, 3)

In [29]:
array3_.shape

(3, 2, 3)

# Shallow Deep copy of an Array

In [30]:
import copy

In [145]:
comp = [[1,2,3],3,5,7]

In [32]:
#Shallow copy
a=np.copy(comp)
a

array([list([1, 2, 3]), 3, 5, 7], dtype=object)

In [33]:
#Numpy can only do shallow copy.
#For Deep copy we need Copy library.
b=copy.deepcopy(comp)
b

[[1, 2, 3], 3, 5, 7]

In [35]:
id(comp)

1989353851656

In [36]:
id(a)

1989353986288

In [37]:
id(b)

1989353940872

In [38]:
id(comp[0])

1989353942984

In [39]:
id(a[0])

1989353942984

In [40]:
id(b[0])

1989353941448

In [41]:
# comp[0] and a[0] have same id. Shallow copy
comp[0].append(3)

In [146]:
comp

[[1, 2, 3], 3, 5, 7]

In [43]:
a

array([list([1, 2, 3, 3]), 3, 5, 7], dtype=object)

In [44]:
b

[[1, 2, 3], 3, 5, 7]

In [45]:
comp.append(4)

In [46]:
comp

[[1, 2, 3, 3], 3, 5, 7, 4]

In [47]:
a

array([list([1, 2, 3, 3]), 3, 5, 7], dtype=object)

In [48]:
b

[[1, 2, 3], 3, 5, 7]

# Array with Placeholders

In [50]:
np.zeros(4)

array([0., 0., 0., 0.])

In [51]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
np.eye(4,5) #Identity Matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [55]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [56]:
np.linspace(start=0,stop=10,num=11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [57]:
np.arange(start=0,stop=10,step=2)

array([0, 2, 4, 6, 8])

In [59]:
np.full(shape=(5,6),fill_value=8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [60]:
np.random.rand(7) #7 random numbers between 0 & 1

array([0.20843845, 0.8224142 , 0.45086563, 0.75013681, 0.72343417,
       0.1213653 , 0.85803829])

In [61]:
np.random.randn(7) #7 random numbers from the data which has mean=0 and s.d.=1

array([ 0.82595812, -1.32045678, -0.66123675,  0.80075079,  0.40766091,
        0.61131781,  0.74338912])

In [63]:
np.random.randint(0,8,size=(4,5)) #random integers between 0 to 8

array([[7, 2, 7, 4, 4],
       [5, 7, 3, 5, 3],
       [2, 4, 4, 1, 7],
       [3, 0, 0, 0, 5]])

In [65]:
l=[1,2,3]
np.random.choice(l,size=(2,4),p=[0.5,0.3,0.2]) #values from l which probabilities in p
#if we just write 5 in place of l it will assume np.arange(5)

array([[3, 1, 2, 1],
       [3, 2, 1, 3]])

In [66]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [67]:
np.empty((3,4)) #Takes totally random values

array([[9.82858095e-312, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.33664410e+160, 5.45311620e-090,
        3.73455099e-061],
       [2.36594827e+179, 1.43961675e+160, 3.99910963e+252,
        4.93432906e+257]])

# Inspect an Array

In [68]:
array = np.random.randint(0,10,size=10)
array2 = np.eye(4,5)
array2[2][2] = np.NaN
array2

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0., nan,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.]])

In [72]:
array.shape #(row,column)

(10,)

In [73]:
array2.shape

(4, 5)

In [74]:
array.size #row*column

10

In [77]:
len(array) #rows

10

In [78]:
len(array2)

4

In [81]:
array.ndim #dimension

1

In [82]:
array2.ndim

2

In [84]:
array.dtype #datatype

dtype('int32')

In [85]:
array2.dtype

dtype('float64')

In [88]:
a.dtype #object

dtype('O')

In [89]:
array.astype(np.float).dtype #Change datatype

dtype('float64')

In [90]:
array2.astype(np.object).dtype

dtype('O')

In [110]:
a=[1,2,3,4,5,6,7,8,9,10,11,12]
b=[4,5,6,7,6,8,9,0,1,2,3,12]
a=np.array(a)
b=np.array(b)

In [111]:
np.sum(a)

78

In [112]:
np.mean(a)

6.5

In [113]:
np.median(a)

6.5

In [114]:
np.cumsum(a) #Cumulative sum

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66, 78], dtype=int32)

In [115]:
np.std(a) #Standard Deviation

3.452052529534663

In [116]:
np.corrcoef(a,b) #Covarience matrix as corr(a,a) corr(a,b) corr(b,a) corr(b,b)

array([[ 1.        , -0.01804325],
       [-0.01804325,  1.        ]])

In [117]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162])

In [118]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05])

In [119]:
np.power(a,2)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [120]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665])

In [121]:
np.log10(a)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ,
       1.04139269, 1.07918125])

In [122]:
np.divide(a,5)

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4])

In [123]:
np.sum(a)

78

In [124]:
np.add(a,b)

array([ 5,  7,  9, 11, 11, 14, 16,  8, 10, 12, 14, 24])

In [125]:
a+b

array([ 5,  7,  9, 11, 11, 14, 16,  8, 10, 12, 14, 24])

In [126]:
np.subtract(a,b)

array([-3, -3, -3, -3, -1, -2, -2,  8,  8,  8,  8,  0])

In [127]:
a-b

array([-3, -3, -3, -3, -1, -2, -2,  8,  8,  8,  8,  0])

In [128]:
np.multiply(a,b)

array([  4,  10,  18,  28,  30,  48,  63,   0,   9,  20,  33, 144])

In [129]:
a*b

array([  4,  10,  18,  28,  30,  48,  63,   0,   9,  20,  33, 144])

In [130]:
np.divide(a,b)

D:\Gaurav\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([0.25      , 0.4       , 0.5       , 0.57142857, 0.83333333,
       0.75      , 0.77777778,        inf, 9.        , 5.        ,
       3.66666667, 1.        ])

In [131]:
a/b

D:\Gaurav\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([0.25      , 0.4       , 0.5       , 0.57142857, 0.83333333,
       0.75      , 0.77777778,        inf, 9.        , 5.        ,
       3.66666667, 1.        ])

In [132]:
np.dot(a,b)

407

In [134]:
a.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [135]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [136]:
a[0]

1

In [137]:
a[:3]

array([1, 2, 3])

In [138]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [139]:
a>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True])

In [140]:
np.insert(arr=array,obj=0,values=[1,2,3])

array([1, 2, 3, 1, 6, 5, 9, 7, 7, 7, 4, 3, 7])

In [147]:
comp.insert(0,[1,2])
comp

[[1, 2], [1, 2, 3], 3, 5, 7]

In [148]:
np.delete(array,[1,2,3]) #Delete indexes 1,2 & 3

array([1, 7, 7, 7, 4, 3, 7])

In [149]:
np.where(array==4)

(array([7], dtype=int64),)

In [151]:
np.delete(array,np.where(array==4),axis=0)

array([1, 6, 5, 9, 7, 7, 7, 3, 7])

In [154]:
array.resize(3,3) #Array changes

In [155]:
array

array([[1, 6, 5],
       [9, 7, 7],
       [7, 4, 3]])

In [158]:
array.reshape(1,9) #Array does not change

array([[1, 6, 5, 9, 7, 7, 7, 4, 3]])

In [159]:
array

array([[1, 6, 5],
       [9, 7, 7],
       [7, 4, 3]])

In [160]:
array.reshape(-1,1)

array([[1],
       [6],
       [5],
       [9],
       [7],
       [7],
       [7],
       [4],
       [3]])

In [161]:
array.reshape(1,-1)

array([[1, 6, 5, 9, 7, 7, 7, 4, 3]])

In [162]:
array.reshape(-1,3)

array([[1, 6, 5],
       [9, 7, 7],
       [7, 4, 3]])

In [163]:
array.T

array([[1, 9, 7],
       [6, 7, 4],
       [5, 7, 3]])

In [165]:
np.ravel(array) #Make one row

array([1, 6, 5, 9, 7, 7, 7, 4, 3])

In [167]:
array1 = np.arange(1,11,1).reshape(2,5)
array2 = np.arange(11,16,1).reshape(1,5)

In [168]:
array1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [169]:
array2

array([[11, 12, 13, 14, 15]])

In [173]:
array3 = np.concatenate((array1,array2),axis=0) #row wise operation axis=0
array3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [174]:
np.concatenate((array3,array2.T[:3]),axis=1) #column wise operation axis=1

array([[ 1,  2,  3,  4,  5, 11],
       [ 6,  7,  8,  9, 10, 12],
       [11, 12, 13, 14, 15, 13]])

In [175]:
np.column_stack((array1[0],array2[0]))

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15]])

In [177]:
np.vsplit(array3,3) #verticle split equally

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15]])]

In [178]:
np.hsplit(array3,5)

[array([[ 1],
        [ 6],
        [11]]), array([[ 2],
        [ 7],
        [12]]), array([[ 3],
        [ 8],
        [13]]), array([[ 4],
        [ 9],
        [14]]), array([[ 5],
        [10],
        [15]])]

In [4]:
arr = np.array(np.random.randint(1,1000,10))
arr2 = np.append(arr,[3])

In [5]:
arr

array([156, 701,  45, 601, 560, 432, 472, 318, 466, 747])

In [6]:
arr2

array([156, 701,  45, 601, 560, 432, 472, 318, 466, 747,   3])

In [10]:
np.mean(arr) #Faster

449.8

In [11]:
arr.mean()

449.8

In [13]:
arr2.shape

(11,)